name: Print Message
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
      - name: Print Push Message
        if: github.event_name == 'push'
        run: echo "new Push Detected on master branch"
      - name: Print Pull Request Message
        if: github.event_name ==  'pull_request'
        run: echo "new Pull Request Detected on master branch"